param(
  [string]$WinDivertDir = "",
  [string]$OutputDir = "",
  [switch]$SkipWinDivert
)

$ErrorActionPreference = "Stop"

function Write-Step($Message) {
  Write-Host ""
  Write-Host "==> $Message" -ForegroundColor Cyan
}

function Test-WinDivertDir($Dir) {
  if (-not $Dir) {
    return $false
  }
  return (Test-Path (Join-Path $Dir "WinDivert.dll")) -and (Test-Path (Join-Path $Dir "WinDivert64.sys"))
}

function Find-WinDivertDir($RepoRoot, $OutputDir) {
  $candidates = @(
    $OutputDir,
    (Join-Path $RepoRoot "windows-backend\WinDivert\x64"),
    (Join-Path $RepoRoot "windows-backend\WinDivert"),
    (Join-Path $RepoRoot "third_party\WinDivert\x64"),
    (Join-Path $RepoRoot "third_party\WinDivert"),
    (Join-Path $RepoRoot "WinDivert\x64"),
    (Join-Path $RepoRoot "WinDivert")
  )

  foreach ($candidate in $candidates) {
    if (Test-WinDivertDir $candidate) {
      return $candidate
    }
  }

  $downloads = Join-Path $env:USERPROFILE "Downloads"
  if (Test-Path $downloads) {
    $dll = Get-ChildItem -Path $downloads -Filter "WinDivert.dll" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($dll -and (Test-WinDivertDir $dll.DirectoryName)) {
      return $dll.DirectoryName
    }
  }

  return ""
}

function Copy-IfDifferent($Source, $DestinationDir) {
  $destination = Join-Path $DestinationDir (Split-Path -Leaf $Source)
  $sourcePath = [System.IO.Path]::GetFullPath($Source)
  $destinationPath = [System.IO.Path]::GetFullPath($destination)
  if ($sourcePath -ieq $destinationPath) {
    Write-Host "Already in place: $destinationPath"
    return
  }

  Copy-Item $Source $DestinationDir -Force
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$windowsBackendDir = Split-Path -Parent $scriptDir
$repoRoot = Split-Path -Parent $windowsBackendDir
$project = Join-Path $repoRoot "windows-backend\Weaknet.WinDivertShaper\Weaknet.WinDivertShaper.csproj"

if (-not $OutputDir) {
  $OutputDir = Join-Path $repoRoot "windows-backend\dist\win-x64"
}

New-Item -ItemType Directory -Force $OutputDir | Out-Null

Write-Host "Weaknet Windows package build"
Write-Host "Repo root: $repoRoot"
Write-Host "Output: $OutputDir"

Write-Step "Checking dotnet SDK"
$dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
if (-not $dotnet) {
  throw "dotnet was not found. Build machine needs .NET 8 SDK, but end users do not."
}
dotnet --version

Write-Step "Publishing self-contained backend"
dotnet publish $project `
  -f net8.0 `
  -c Release `
  -r win-x64 `
  --self-contained true `
  -p:PublishSingleFile=false `
  -p:DebugType=none `
  -p:DebugSymbols=false `
  -o $OutputDir

$exe = Join-Path $OutputDir "Weaknet.WinDivertShaper.exe"
if (-not (Test-Path $exe)) {
  throw "Publish completed but executable was not found: $exe"
}

if (-not $SkipWinDivert) {
  Write-Step "Bundling WinDivert"
  if (-not (Test-WinDivertDir $WinDivertDir)) {
    $WinDivertDir = Find-WinDivertDir $repoRoot $OutputDir
  }
  if (-not (Test-WinDivertDir $WinDivertDir)) {
    throw "Could not find WinDivert.dll and WinDivert64.sys. Pass -WinDivertDir with the folder that contains both files."
  }
  Write-Host "Using WinDivert: $WinDivertDir"
  Copy-IfDifferent (Join-Path $WinDivertDir "WinDivert.dll") $OutputDir
  Copy-IfDifferent (Join-Path $WinDivertDir "WinDivert64.sys") $OutputDir
}

$readme = Join-Path $OutputDir "WEAKNET_WINDOWS_PACKAGE.txt"
@"
Weaknet Windows backend package

This directory is generated by windows-backend\scripts\build-win32-package.ps1.

Included:
- Weaknet.WinDivertShaper.exe published self-contained for win-x64.
- WinDivert.dll and WinDivert64.sys, when WinDivert was found or supplied.

End users do not need to install .NET SDK or .NET Runtime for this backend.
WinDivert still requires the main weaknet service to run as Administrator on Windows.

Expected launch path from the repo:
- Run windows-backend\scripts\open-weaknet-win32.cmd as Administrator.
- Open http://127.0.0.1:8123
"@ | Set-Content -Path $readme -Encoding UTF8

Write-Step "Done"
Get-ChildItem $OutputDir | Select-Object Name, Length, LastWriteTime | Format-Table
